
package service.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "utsTutorService", targetNamespace = "http://soap.service/", wsdlLocation = "http://localhost:8080/services/UtsTutor?wsdl")
public class UtsTutorService
    extends Service
{

    private final static URL UTSTUTORSERVICE_WSDL_LOCATION;
    private final static WebServiceException UTSTUTORSERVICE_EXCEPTION;
    private final static QName UTSTUTORSERVICE_QNAME = new QName("http://soap.service/", "utsTutorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/services/UtsTutor?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UTSTUTORSERVICE_WSDL_LOCATION = url;
        UTSTUTORSERVICE_EXCEPTION = e;
    }

    public UtsTutorService() {
        super(__getWsdlLocation(), UTSTUTORSERVICE_QNAME);
    }

    public UtsTutorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UTSTUTORSERVICE_QNAME, features);
    }

    public UtsTutorService(URL wsdlLocation) {
        super(wsdlLocation, UTSTUTORSERVICE_QNAME);
    }

    public UtsTutorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UTSTUTORSERVICE_QNAME, features);
    }

    public UtsTutorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UtsTutorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UtsTutorSoap
     */
    @WebEndpoint(name = "UtsTutorSoapPort")
    public UtsTutorSoap getUtsTutorSoapPort() {
        return super.getPort(new QName("http://soap.service/", "UtsTutorSoapPort"), UtsTutorSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UtsTutorSoap
     */
    @WebEndpoint(name = "UtsTutorSoapPort")
    public UtsTutorSoap getUtsTutorSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.service/", "UtsTutorSoapPort"), UtsTutorSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UTSTUTORSERVICE_EXCEPTION!= null) {
            throw UTSTUTORSERVICE_EXCEPTION;
        }
        return UTSTUTORSERVICE_WSDL_LOCATION;
    }

}
