
package service.soap.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UtsTutorSoap", targetNamespace = "http://soap.service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtsTutorSoap {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns service.soap.client.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://soap.service/", className = "service.soap.client.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://soap.service/", className = "service.soap.client.LoginResponse")
    @Action(input = "http://soap.service/UtsTutorSoap/loginRequest", output = "http://soap.service/UtsTutorSoap/loginResponse")
    public User login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelBooking", targetNamespace = "http://soap.service/", className = "service.soap.client.CancelBooking")
    @ResponseWrapper(localName = "cancelBookingResponse", targetNamespace = "http://soap.service/", className = "service.soap.client.CancelBookingResponse")
    @Action(input = "http://soap.service/UtsTutorSoap/cancelBookingRequest", output = "http://soap.service/UtsTutorSoap/cancelBookingResponse")
    public Object cancelBooking(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        User arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createBooking", targetNamespace = "http://soap.service/", className = "service.soap.client.CreateBooking")
    @ResponseWrapper(localName = "createBookingResponse", targetNamespace = "http://soap.service/", className = "service.soap.client.CreateBookingResponse")
    @Action(input = "http://soap.service/UtsTutorSoap/createBookingRequest", output = "http://soap.service/UtsTutorSoap/createBookingResponse")
    public Object createBooking(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        User arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<service.soap.client.Booking>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookings", targetNamespace = "http://soap.service/", className = "service.soap.client.GetBookings")
    @ResponseWrapper(localName = "getBookingsResponse", targetNamespace = "http://soap.service/", className = "service.soap.client.GetBookingsResponse")
    @Action(input = "http://soap.service/UtsTutorSoap/getBookingsRequest", output = "http://soap.service/UtsTutorSoap/getBookingsResponse")
    public List<Booking> getBookings(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editAccount", targetNamespace = "http://soap.service/", className = "service.soap.client.EditAccount")
    @ResponseWrapper(localName = "editAccountResponse", targetNamespace = "http://soap.service/", className = "service.soap.client.EditAccountResponse")
    @Action(input = "http://soap.service/UtsTutorSoap/editAccountRequest", output = "http://soap.service/UtsTutorSoap/editAccountResponse")
    public Object editAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        User arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelAccount", targetNamespace = "http://soap.service/", className = "service.soap.client.CancelAccount")
    @ResponseWrapper(localName = "cancelAccountResponse", targetNamespace = "http://soap.service/", className = "service.soap.client.CancelAccountResponse")
    @Action(input = "http://soap.service/UtsTutorSoap/cancelAccountRequest", output = "http://soap.service/UtsTutorSoap/cancelAccountResponse")
    public boolean cancelAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "completeBooking", targetNamespace = "http://soap.service/", className = "service.soap.client.CompleteBooking")
    @ResponseWrapper(localName = "completeBookingResponse", targetNamespace = "http://soap.service/", className = "service.soap.client.CompleteBookingResponse")
    @Action(input = "http://soap.service/UtsTutorSoap/completeBookingRequest", output = "http://soap.service/UtsTutorSoap/completeBookingResponse")
    public Object completeBooking(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        User arg1);

}
